# Generated by Django 6.0.6 on 2026-06-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppAdministracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoapp_administracion',
            name='last_conection',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
