# Generated by Django 6.0.6 on 2026-06-15 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Cuidados',
            fields=[
                ('id_cuidado', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro cuidado')),
                ('publico', models.CharField(choices=[('NIÑOS', 'Niños'), ('PROFESORES', 'Profesores'), ('CANTANTES_ACTORES', 'Cantantes y/o Actores'), ('LOCUTORES', 'Locutores'), ('PUBLICO_GENERAL', 'Público General')], default='PUBLICO_GENERAL', max_length=20, verbose_name='Público Objetivo')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido de cuidados')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cuidados/imagenes/', verbose_name='Imagen')),
                ('fuente', models.URLField(blank=True, max_length=500, null=True, verbose_name='Fuentes Científicas')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidados_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Cuidado',
                'verbose_name_plural': 'Cuidados',
                'db_table': 'FonoApp_Cuidados',
                'ordering': ['id_cuidado'],
                'managed': True,
            },
        ),
    ]
