# Generated by Django 6.0.5 on 2026-05-23 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Informacion',
            fields=[
                ('id_informacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Informacion')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('SA', 'Salud Animal'), ('CU', 'Cuidados Básicos'), ('NU', 'Nutrición'), ('TI', 'Tips y Consejos')], default='CU', max_length=2, verbose_name='Categoría')),
                ('contenido', models.TextField(verbose_name='Cuerpo información')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
                'db_table': 'FonoApp_Informacion',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Informacion_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informacion/imagenes/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('informacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='FonoAppInformacion.fonoapp_informacion')),
            ],
            options={
                'verbose_name': 'Imagen de la Informacion',
                'verbose_name_plural': 'Imágenes de la Informacion',
                'db_table': 'FonoApp_Informacion_Imagen',
            },
        ),
    ]
