# Generated by Django 6.0.6 on 2026-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppInformacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_informacion',
            name='categoria',
            field=models.CharField(choices=[('SA', 'ninos'), ('CU', 'profesores'), ('NU', 'cantantesactores'), ('TI', 'locutores'), ('GE', 'general')], default='GE', max_length=2, verbose_name='Categoría'),
        ),
    ]
