# Generated by Django 6.0.6 on 2026-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppInformacion', '0002_alter_fonoapp_informacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_informacion',
            name='categoria',
            field=models.CharField(choices=[('NI', 'ninos'), ('PO', 'profesores'), ('CA', 'cantantesactores'), ('LO', 'locutores'), ('GE', 'general')], default='GE', max_length=2, verbose_name='Categoría'),
        ),
    ]
