# Generated by Django 6.0.5 on 2026-05-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo noticia')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(verbose_name='Cuerpo de la noticia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'FonoApp_Noticias',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Noticia_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/imagenes/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='FonoAppNoticias.fonoapp_noticias')),
            ],
            options={
                'verbose_name': 'Imagen de Noticia',
                'verbose_name_plural': 'Imágenes de Noticias',
                'db_table': 'FonoApp_Noticia_Imagen',
            },
        ),
    ]
